- name: Push to Hugging Face
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    git clone https://AremuTaiwo:$HF_TOKEN@huggingface.co/spaces/AremuTaiwo/Rag-Pipeline hf_space
    cd hf_space

    git config user.name "github-actions"
    git config user.email "actions@github.com"

    git pull origin main --rebase

    cp -r ../* .

    git add .
    git commit -m "auto deploy" || echo "no changes"
    git push origin main